// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportDataService;

#nullable disable

namespace ulasim_veri_servisi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818055233_UpdateGtfsImportRunLastModifiedType")]
    partial class UpdateGtfsImportRunLastModifiedType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransportDataService.Domain.ExternalApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseDurationMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ExternalApiLogs");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgencyLang")
                        .HasColumnType("text");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("text");

                    b.Property<string>("AgencyTimezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.HasIndex("AgencyId", "GtfsImportRunId")
                        .IsUnique();

                    b.ToTable("GtfsAgencies");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.ToTable("GtfsCalendars");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsCalendarDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.ToTable("GtfsCalendarDates");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsImportPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedRecordCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.ToTable("GtfsImportPhases");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FailedRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FeedEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FeedStartDate")
                        .HasColumnType("date");

                    b.Property<string>("FeedVersion")
                        .HasColumnType("text");

                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RouteCount")
                        .HasColumnType("integer");

                    b.Property<int>("ShapePointCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StopCount")
                        .HasColumnType("integer");

                    b.Property<int>("StopTimeCount")
                        .HasColumnType("integer");

                    b.Property<int>("TripCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.ToTable("GtfsImportRuns");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteColor")
                        .HasColumnType("text");

                    b.Property<string>("RouteDesc")
                        .HasColumnType("text");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteLongName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("text");

                    b.Property<int?>("RouteType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.HasIndex("RouteId", "GtfsImportRunId")
                        .IsUnique();

                    b.ToTable("GtfsRoutes");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsShapePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.ToTable("GtfsShapePoints");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text");

                    b.Property<string>("StopCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StopDesc")
                        .HasColumnType("text");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StopUrl")
                        .HasColumnType("text");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.HasIndex("StopId", "GtfsImportRunId")
                        .IsUnique();

                    b.ToTable("GtfsStops");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsStopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArrivalSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ArrivalTimeRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartureSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureTimeRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsStopId")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsTripId")
                        .HasColumnType("integer");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.HasIndex("GtfsStopId");

                    b.HasIndex("GtfsTripId", "StopSequence");

                    b.HasIndex("StopId", "DepartureSeconds", "GtfsTripId");

                    b.ToTable("GtfsStopTimes");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("FromStopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSameCoordinateCluster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSameParentStation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSamePhysicalStop")
                        .HasColumnType("boolean");

                    b.Property<string>("ToStopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WalkingTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId", "FromStopId", "DistanceMeters");

                    b.HasIndex("GtfsImportRunId", "FromStopId", "ToStopId")
                        .IsUnique();

                    b.ToTable("GtfsTransfers");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsRouteId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShapeId")
                        .HasColumnType("text");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("text");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GtfsImportRunId");

                    b.HasIndex("GtfsRouteId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TripId", "GtfsImportRunId")
                        .IsUnique();

                    b.ToTable("GtfsTrips");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTripStopSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GtfsImportRunId")
                        .HasColumnType("integer");

                    b.Property<int>("GtfsTripId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("StopSequences")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("GtfsTripId");

                    b.HasIndex("GtfsImportRunId", "GtfsTripId")
                        .IsUnique();

                    b.ToTable("GtfsTripStopSummaries");
                });

            modelBuilder.Entity("TransportDataService.Domain.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FailedRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedRecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpdatedRecordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("TransportDataService.Domain.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalStopId")
                        .IsUnique();

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("TransportDataService.Domain.StopRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StopId", "RouteNumber")
                        .IsUnique();

                    b.ToTable("StopRoutes");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsAgency", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsCalendar", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsCalendarDate", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsImportPhase", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany("Phases")
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsRoute", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsShapePoint", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsStop", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsStopTime", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportDataService.Domain.GtfsStop", "Stop")
                        .WithMany("StopTimes")
                        .HasForeignKey("GtfsStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportDataService.Domain.GtfsTrip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("GtfsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTransfer", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTrip", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportDataService.Domain.GtfsRoute", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("GtfsRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTripStopSummary", b =>
                {
                    b.HasOne("TransportDataService.Domain.GtfsImportRun", "GtfsImportRun")
                        .WithMany()
                        .HasForeignKey("GtfsImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportDataService.Domain.GtfsTrip", "Trip")
                        .WithMany()
                        .HasForeignKey("GtfsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GtfsImportRun");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransportDataService.Domain.StopRoute", b =>
                {
                    b.HasOne("TransportDataService.Domain.Stop", "Stop")
                        .WithMany("StopRoutes")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsImportRun", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsRoute", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsStop", b =>
                {
                    b.Navigation("StopTimes");
                });

            modelBuilder.Entity("TransportDataService.Domain.GtfsTrip", b =>
                {
                    b.Navigation("StopTimes");
                });

            modelBuilder.Entity("TransportDataService.Domain.Stop", b =>
                {
                    b.Navigation("StopRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
